### PR TITLE
Here's a fix for the wrap-params issue

### PR DESCRIPTION
**Pull request by abedra**
I played around with several variations of this, but in the end it seems best to just fall out to nil when it can't decode a parameter.  I tried this by patching the jar in place on my project and things worked just fine.

### CODE REVIEW

**Comment by weavejester** [comment]
Could you possibly write a quick test for this? I like to keep up to date with my regression tests.

**Comment by abedra** [comment]
On 06/24/2011 03:25 PM, weavejester wrote:

> Could you possibly write a quick test for this? I like to keep up to date with my regression tests.
> 
> Not a problem at all.  I'll send over another pull request in a few minutes.

Aaron

**Comment by abedra** [comment]
ok i have checked in the exact test case that was previously failing for me.

**Comment by weavejester** [comment]
I squashed your commits and merged them in. Thanks for the fix!

**Comment by abedra** [comment]
Thanks!  Any chance a release can be pushed?

**Comment by weavejester** [comment]
I'll try and push out a release tonight. I have a few other fixes I was to make as well.

**Comment by abedra** [comment]
Awesome! Let me know if I can help in any way

**Comment by weavejester** [comment]
I've released 0.3.9 with this fix included.

**Comment by abedra** [comment]
Thanks!

**Pull request closed without merging**
