### PR TITLE
add mime-type

### PR DESCRIPTION
**Pull request by hozumi**
Hi,
I wanted a mime-type of ".htc" and after googled I found that there are a lack of mime-types in default-mime-type.
So I added all mime-types which is not in default-mime-type.
I used following page as a reference, but I don't sure that this is a proper list.
I think this is harmless change.
http://www.w3schools.com/media/media_mimeref.asp

added mime-type:
{"323" "text/h323",
 "acx" "application/internet-property-stream",
 "aif" "audio/x-aiff",
 "aifc" "audio/x-aiff",
 "aiff" "audio/x-aiff",
 "asf" "video/x-ms-asf",
 "asr" "video/x-ms-asf",
 "asx" "video/x-ms-asf",
 "au" "audio/basic",
 "axs" "application/olescript",
 "bas" "text/plain",
 "bcpio" "application/x-bcpio",
 "c" "text/plain",
 "cat" "application/vnd.ms-pkiseccat",
 "cdf" "application/x-cdf",
 "clp" "application/x-msclip",
 "cmx" "image/x-cmx",
 "cod" "image/cis-cod",
 "cpio" "application/x-cpio",
 "crd" "application/x-mscardfile",
 "csh" "application/x-csh",
 "dcr" "application/x-director",
 "der" "application/x-x509-ca-cert",
 "dir" "application/x-director",
 "dot" "application/msword",
 "dxr" "application/x-director",
 "evy" "application/envoy",
 "fif" "application/fractals",
 "flr" "x-world/x-vrml",
 "gtar" "application/x-gtar",
 "h" "text/plain",
 "hdf" "application/x-hdf",
 "hlp" "application/winhlp",
 "hqx" "application/mac-binhex40",
 "hta" "application/hta",
 "htc" "text/x-component",
 "htt" "text/webviewhtml",
 "ief" "image/ief",
 "iii" "application/x-iphone",
 "ins" "application/x-internet-signup",
 "isp" "application/x-internet-signup",
 "jfif" "image/pipeg",
 "latex" "application/x-latex",
 "lsf" "video/x-la-asf",
 "lsx" "video/x-la-asf",
 "m13" "application/x-msmediaview",
 "m14" "application/x-msmediaview",
 "m3u" "audio/x-mpegurl",
 "man" "application/x-troff-man",
 "mdb" "application/x-msaccess",
 "me" "application/x-troff-me",
 "mht" "message/rfc822",
 "mhtml" "message/rfc822",
 "mid" "audio/mid",
 "mny" "application/x-msmoney",
 "movie" "video/x-sgi-movie",
 "mp2" "video/mpeg",
 "mpa" "video/mpeg",
 "mpp" "application/vnd.ms-project",
 "mpv2" "video/mpeg",
 "ms" "application/x-troff-ms",
 "mvb" "application/x-msmediaview",
 "nws" "message/rfc822",
 "oda" "application/oda",
 "p10" "application/pkcs10",
 "p12" "application/x-pkcs12",
 "p7b" "application/x-pkcs7-certificates",
 "p7c" "application/x-pkcs7-mime",
 "p7m" "application/x-pkcs7-mime",
 "p7r" "application/x-pkcs7-certreqresp",
 "p7s" "application/x-pkcs7-signature",
 "pfx" "application/x-pkcs12",
 "pko" "application/ynd.ms-pkipko",
 "pma" "application/x-perfmon",
 "pmc" "application/x-perfmon",
 "pml" "application/x-perfmon",
 "pmr" "application/x-perfmon",
 "pmw" "application/x-perfmon",
 "pot" "application/vnd.ms-powerpoint",
 "pps" "application/vnd.ms-powerpoint",
 "prf" "application/pics-rules",
 "pub" "application/x-mspublisher",
 "ra" "audio/x-pn-realaudio",
 "ram" "audio/x-pn-realaudio",
 "rgb" "image/x-rgb",
 "rmi" "audio/mid",
 "roff" "application/x-troff",
 "rtx" "text/richtext",
 "scd" "application/x-msschedule",
 "sct" "text/scriptlet",
 "setpay" "application/set-payment-initiation",
 "setreg" "application/set-registration-initiation",
 "sh" "application/x-sh",
 "shar" "application/x-shar",
 "sit" "application/x-stuffit",
 "snd" "audio/basic",
 "spc" "application/x-pkcs7-certificates",
 "spl" "application/futuresplash",
 "src" "application/x-wais-source",
 "sst" "application/vnd.ms-pkicertstore",
 "stl" "application/vnd.ms-pkistl",
 "stm" "text/html",
 "sv4cpio" "application/x-sv4cpio",
 "sv4crc" "application/x-sv4crc",
 "t" "application/x-troff",
 "tcl" "application/x-tcl",
 "tex" "application/x-tex",
 "texi" "application/x-texinfo",
 "texinfo" "application/x-texinfo",
 "tgz" "application/x-compressed",
 "tr" "application/x-troff",
 "trm" "application/x-msterminal",
 "tsv" "text/tab-separated-values",
 "uls" "text/iuls",
 "ustar" "application/x-ustar",
 "vcf" "text/x-vcard",
 "vrml" "x-world/x-vrml",
 "wav" "audio/x-wav",
 "wcm" "application/vnd.ms-works",
 "wdb" "application/vnd.ms-works",
 "wks" "application/vnd.ms-works",
 "wmf" "application/x-msmetafile",
 "wps" "application/vnd.ms-works",
 "wri" "application/x-mswrite",
 "wrl" "x-world/x-vrml",
 "wrz" "x-world/x-vrml",
 "xaf" "x-world/x-vrml",
 "xla" "application/vnd.ms-excel",
 "xlc" "application/vnd.ms-excel",
 "xlm" "application/vnd.ms-excel",
 "xlt" "application/vnd.ms-excel",
 "xlw" "application/vnd.ms-excel",
 "xof" "x-world/x-vrml",
 "z" "application/x-compress"}

Thanks.

### CODE REVIEW

**Comment by weavejester** [comment]
I'll look into adding these. I'm not sure I completely trust the w3schools list though, as I found it had a few errors. For example, "js" is listed as "application/x-javascript", when it should be "application/javascript".

However, do you know you can specify a map with your own mime-types in the file-info and content-type middleware? Your mime-type map will be merged with the default map, with your extension mapping taking priority over the defaults.

**Comment by hozumi** [comment]
Hi, I also not sure this list. So, as you say, I should use file-info arg option.
Thanks.

**Comment by hozumi** [comment]
close

**Comment by weavejester** [comment]
I'll definitely add in some of those extensions, like htc and m3u. But I'll check them against other sources first, just to make sure w3schools hasn't screwed up. Wikipedia has got quite a lot of information about file formats, and I trust that more than w3schools :)

**Comment by hozumi** [comment]
Ok, to add a few assured mime-type is right way.

**Pull request closed without merging**
